const PORT = Number(process.env.PORT || 8787);
const REQUEST_TIMEOUT_MS = Number(process.env.REQUEST_TIMEOUT_MS || 3500);
const CATEGORY_RADIUS_METERS = 1300;
const LOCAL_NAME_RADIUS_METERS = 96560;
const SEARCH_CACHE_TTL_MS = Number(process.env.SEARCH_CACHE_TTL_MS || 300000);
const GEOAPIFY_API_KEY = process.env.GEOAPIFY_API_KEY || "";

module.exports = {
  PORT,
  REQUEST_TIMEOUT_MS,
  CATEGORY_RADIUS_METERS,
  LOCAL_NAME_RADIUS_METERS,
  SEARCH_CACHE_TTL_MS,
  GEOAPIFY_API_KEY
};
